models/languages/de.php

since this is my first pull request, I hope I'm doing this right.

added German translation

---

forms/form_user.php
install/install_root_user.php
models/authorization.php
models/db_functions.php
models/error_functions.php
models/rb.php
models/template_functions.php

Replaced instances of and with &&, according to #29

Replaced and with &&

---

forms/form_user.php
install/install_root_user.php
models/authorization.php
models/db_functions.php
models/error_functions.php
models/rb.php
models/template_functions.php

Reverts alexweissman/UserFrosting#253

Revert "Replaced and with &&"

---

install/install_db.php
install/wizard_root_user.php
models/db-settings.php

A fix for https://github.com/alexweissman/UserFrosting/issues/249.

Issue 249 install message db prefix

---

models/languages/nl.php

Dutch translation for those from the Netherlands.

added Dutch translation

---

userfrosting/controllers/AccountController.php
userfrosting/controllers/BaseController.php
userfrosting/initialize.php
userfrosting/models/mysql/MySqlSiteSettings.php
userfrosting/templates/common/components/footer.html
userfrosting/templates/common/home.html
userfrosting/templates/common/register.html
userfrosting/templates/themes/default/components/footer.html
userfrosting/templates/themes/default/dashboard.html

1. Moved generate Captcha to base class
2. Updated themes to get the Site Title dynamically
3. Has the plugin init code
Updated the userfrosting-oauth plugin code on the other branch.

Suggested changes to UF Control Classes to Accomodate Plugins

---

userfrosting/locale/th_TH.php

Add Thai language

---

userfrosting/locale/es_ES.php

Small changes to improve the Spanish translation

Improve Spanish translation

---

tutorials/lesson-2-process-form/index.html

Reference ID from DB, not as assigned by Eloquent

---

userfrosting/config-userfrosting-example.php
userfrosting/models/UserFrosting.php

Works great for me. I'm eager to here you feedback.

optional enable twig cache

---

userfrosting/config-userfrosting-example.php
userfrosting/models/UserFrosting.php

Reverts userfrosting/UserFrosting#493

Revert "optional enable twig cache"

---

public/js/userfrosting.js

The problem was the strict comparison.

Solution to issue #473

---

userfrosting/composer.json
userfrosting/composer.lock
userfrosting/vendor/composer/ClassLoader.php
userfrosting/vendor/composer/LICENSE
userfrosting/vendor/composer/autoload_files.php
userfrosting/vendor/composer/autoload_real.php
userfrosting/vendor/composer/installed.json
userfrosting/vendor/symfony/translation/Loader/PoFileLoader.php
userfrosting/vendor/symfony/translation/README.md
userfrosting/vendor/symfony/translation/Tests/Loader/PoFileLoaderTest.php
userfrosting/vendor/symfony/translation/Tests/Writer/TranslationWriterTest.php
userfrosting/vendor/symfony/translation/Tests/fixtures/fuzzy-translations.po
userfrosting/vendor/wikimedia/composer-merge-plugin/LICENSE
userfrosting/vendor/wikimedia/composer-merge-plugin/README.md
userfrosting/vendor/wikimedia/composer-merge-plugin/composer.json
userfrosting/vendor/wikimedia/composer-merge-plugin/src/Logger.php
userfrosting/vendor/wikimedia/composer-merge-plugin/src/Merge/ExtraPackage.php
userfrosting/vendor/wikimedia/composer-merge-plugin/src/Merge/MissingFileException.php
userfrosting/vendor/wikimedia/composer-merge-plugin/src/Merge/PluginState.php
userfrosting/vendor/wikimedia/composer-merge-plugin/src/Merge/StabilityFlags.php
userfrosting/vendor/wikimedia/composer-merge-plugin/src/MergePlugin.php

Fixes issue of "wikimedia/composer-merge-plugin" requiring too specific / wrong version of `composer-plugin-api`
Thanks to @agent2020 for finding this issue and reporting in the chat

update "wikimedia/composer-merge-plugin" version

---

USAGE.md
build/package.json

1. Updated instructions in usage file
2. Fixed composer.json in build directory

Installation updates

---

userfrosting/controllers/InstallController.php
userfrosting/models/database/Database.php

Azure SQL Server and SQL Server Support as discussed in  https://github.com/userfrosting/UserFrosting/issues/541.
Tested with Azure SQL Server (site hosted in localhost, database at Microsoft Azure) and MySQL/MariaDB in localhost.

Azure SQL Server and SQL Server Support

---

app/sprinkles/account/bower.json
build/gulpfile.js
build/package.json

Using terminal commands as opposed to an existing bower installation library, as they have proven to be unreliable. Hopefully this works.

Improved vendor asset installation reliability.

---

app/sprinkles/account/migrations/4.0.0-alpha.php
migrations/install.php

Moved root user creation to `account` migrations to prevent crash in the event `account` isn't in load order.

Fixed potential crash in migrations

---

app/sprinkles/account/locale/de_DE/messages.php
app/sprinkles/account/locale/de_DE/validate.php
app/sprinkles/admin/locale/de_DE/messages.php
app/sprinkles/core/config/default.php
app/sprinkles/core/locale/de_DE/errors.php
app/sprinkles/core/locale/de_DE/messages.php
app/sprinkles/core/locale/de_DE/validate.php

German translation added for account/admin/core sprinkles

German translation added

---

app/sprinkles/account/src/Controller/AccountController.php
app/sprinkles/admin/src/Controller/GroupController.php
app/sprinkles/admin/src/Controller/RoleController.php
app/sprinkles/admin/src/Controller/UserController.php
app/sprinkles/core/config/default.php
app/sprinkles/core/src/Mail/Mailer.php

Found a stupid bug in one of my last commits :grin:

Fixed missing translator bug

---

docker-compose.yml
docker/README.md
docker/nginx/Dockerfile
docker/nginx/default.conf
docker/php/Dockerfile

Inspired by #606 I set out to dockerize UserFrosting for a quick development environment. However, my implementation is quite a bit different from #606.

Add docker-compose file for quick start.

---

app/sprinkles/account/locale/es_ES/messages.php
app/sprinkles/account/locale/es_ES/validate.php
app/sprinkles/admin/locale/es_ES/messages.php
app/sprinkles/core/config/default.php
app/sprinkles/core/locale/es_ES/errors.php
app/sprinkles/core/locale/es_ES/messages.php
app/sprinkles/core/locale/es_ES/validate.php

- Fix accent mark
- Unify second person of second person of the singular

 Spanish translations

---

build/gulpfile.esm.js
build/package.json

Always log builds

---

app/sprinkles/admin/asset-bundles.json
app/sprinkles/admin/assets/userfrosting/js/pages/role.js
app/sprinkles/admin/assets/userfrosting/js/widgets/users.js

Fix #1008 and #1010

---

app/sprinkles/core/src/Util/NoCache.php

Fix comment

---

CHANGELOG.md
app/defines.php
app/sprinkles/admin/templates/modals/user-manage-roles.html.twig
app/sprinkles/core/composer.json
app/sprinkles/core/src/Bakery/RouteListCommand.php
app/sprinkles/core/src/Error/Renderer/WhoopsRenderer.php
docker/app/Dockerfile
vagrant/after.sh

Fixes :
- Fix #1162
- Fix #1163
- ~Fix #1164~
Steps to complete before merging:

Release 4.5.1

---

build/package.json

- Updated `@yarnpkg/shell` from `^2.4.1` to `^3.0.0`

Fixes #1168

---

composer.json

Resolves issue #1195 by adding last stable version 1.6.0 of RocketTheme.

Resolve #1195-Update composer.json
