js/userfrosting.js
Base site path note was turning up in console twice whenever page loaded (presumably the function is called twice when setting up the page).
Removed the console.log that prints site path.
No biggie, but was doing my head in!
Continued to use my installation after deleting this line and nothing exploded.
=> Remove debug console log for base site path

models/config.php
This is a fix for https://github.com/alexweissman/UserFrosting/issues/263
$emailDate in models/config.php was formatted incorrectly. 
$emailDate = date('F j, Y');
Formats a date as MONTH DAY, YEAR (i.e. March 21, 2015)
So the email now reads:
=> Bug 263 - Lost password email timestamp format fix

api/user_reset_password.php
Fix for https://github.com/alexweissman/UserFrosting/issues/264.
isset() was the wrong function to use in user_reset_password.php because it always returns true for $_POST and $_GET regardless of whether they contain anything (probably because they are superglobals and thus always available).
count() will work - a URL of the form URL?parameter=value (i.e. http://website.com/api/user_reset_password.php?deny=1f479ccf06482862421e3e265176f4ed) will return 1 and thus work as expected:
$ajax = null;
if (count($_POST)){
$ajax = checkRequestMode("post");
} else {
$ajax = checkRequestMode("get");
}
=> Fix for bug 264 - lost password request error

userfrosting/templates/themes/default/components/footer.html
Setting the footer's container to container-fluid will allow it to be small at a large resolution (such as when the sidebar takes some of the width).
=> fix footer overflow

userfrosting/middleware/usersession/UserSession.php
This fixes an issue with the installation process. If database is not yet set up we are guaranteed a PDO exception. Without knowing if we are installation mode or not we can't be sure if we should show a database error page or just continue routing (ie: to the installation page). So, with this change we just continue routing. The problematic code is left as staged code, to be used if/when we can determine if we are in "installation mode" or not.
=> Fix installation process

app/.env.example
localhost not always resolves correctly (in some MAMP installations) so adding a comment to help future developers save a days of debugging work
=> Adding comment on .env.example to save future developers time

app/sprinkles/account/composer.json, app/sprinkles/account/src/Authenticate/Authenticator.php
=> birke/rememberme update to 2.0 for #635

app/system/Bakery/Command/Setup.php
Stops charset errors at setup.
=> Fix for PostgreSQL setup

app/sprinkles/core/src/Mail/Mailer.php
PHPMailer supports other mailer options such as Mail, Qmail, and sendmail.
Tested with sendmail.
=> Add support for other config['mailer'] options.

app/sprinkles/core/templates/modals/modal.html.twig
Using "is defined" for prevent twig deprecation message:
`Silent display of undefined block "modal_footer" in template "modals/modal.html.twig" is deprecated since version 1.29 and will throw an exception in 2.0. Use the "block('modal_footer') is defined" expression to test for block existence`
https://github.com/twigphp/Twig/commit/ae9b503b17419102dbec3da4a583cf02c3ecf366
=> Avoid twig deprecation warning

app/sprinkles/account/assets/userfrosting/js/pages/register.js, app/sprinkles/account/src/Controller/AccountController.php, app/sprinkles/admin/assets/userfrosting/js/pages/dashboard.js, app/sprinkles/admin/assets/userfrosting/js/pages/group.js, app/sprinkles/admin/assets/userfrosting/js/pages/role.js, app/sprinkles/admin/assets/userfrosting/js/pages/user.js, app/sprinkles/admin/assets/userfrosting/js/widgets/groups.js, app/sprinkles/admin/assets/userfrosting/js/widgets/roles.js, app/sprinkles/admin/assets/userfrosting/js/widgets/users.js, app/sprinkles/admin/src/Controller/GroupController.php, app/sprinkles/admin/src/Controller/PermissionController.php, app/sprinkles/admin/src/Controller/RoleController.php, app/sprinkles/admin/src/Controller/UserController.php, app/sprinkles/admin/templates/pages/group.html.twig, app/sprinkles/admin/templates/pages/role.html.twig, app/sprinkles/admin/templates/pages/user.html.twig
- UserFrosting's `NotFoundException` is now used everywhere in place of Slim's, as it should do.
- Corrected group, role, and user pages to return 404 instead of redirecting.
- Implemented fix to prevent clearing of ufTable URL slug for numerous buttons.
- Moved redirection to client-side for deletion of pages that will result in a 404 on reload.
Addresses #932
=> Better deletion redirects for user, group, and role pages plus related improvements

build/package.json
In preparation for 4.2 stable release, dependencies have been updated to stable.
Update to `del` is major as the release raises the minimum node version (6 and up), a technical breaking change. This isn't an issue, as we already require node 10 or higher.
=> Stabilise build dependencies

app/sprinkles/account/locale/it_IT/messages.php
I noticed the welcome message in Italian is using an incorrect variable for the user's name compared to the other locales, which resulted in the name not being displayed. This PR fixes that.
=> Correct welcome message in the italian locale

app/sprinkles/core/src/Util/CheckEnvironment.php
Provide helpful error message in situation where `cache` `session` or `logs` is accidentally deleted or moved. 
The existing error was: 
This adds `checkDirectories` which provides a more helpful error message:
Because I was unable to come up with a more creative way to prevent `checkPermissions` from returning the generic error message, that check is skipped until the directories actually exist.
=> More helpful error message in checkEnvironment.php

app/sprinkles/account/src/Database/Seeds/DefaultPermissions.php
Fixed sql error when running `php bakery seed DefaultPermissions` as noted in issue #981
=> Fix DefaultPermissions.php SQL Error

app/sprinkles/core/src/Database/Migrator/MigrationLocator.php, app/sprinkles/core/tests/Integration/Database/Migrator/MigrationLocatorTest.php
This ignores any files in Migrations that do not end in .php
It causes problems when scripts, or data, or documentation is
left in the Migrations directory, and the migration task assumes
that they are PHP Classes and crashes.
Signed-Off-By: Rob Thomas <xrobau@gmail.com>
=> Fixes UserFrosting#965 - Ignore files that don't end in .php

app/sprinkles/core/config/default.php
The previous statement would evaluate to true for any value of CSRF_ENABLED.
Using the strict comparison operator means if we set the variable to any false-evaluating values other then boolean false (0, '0', '0.0', '' and so on), then CSRF will be disabled.
getenv() evaluates to boolean false if the environment variable is not set, so I know of no simple way to distinguish between the variable being unset, in which case we want to default to enabling CSRF, and it being explicitly set to boolean false.
=> Respects CSRF_ENABLED environment variable

app/sprinkles/core/src/Bakery/MigrateCleanCommand.php, app/sprinkles/core/src/Database/Migrator/MigrationDependencyAnalyser.php, app/sprinkles/core/src/Database/Migrator/Migrator.php
This command removes stale migrations from the database. These missing migration classes prevent other `migrate:*` commands from running until the missing class files are either added back to the file system or  manually dropped from the `migrations` table. 
I also added a note about the new command when "Unable to find migration..." error messages are given in two of the `Migrator` classes. 
Issue #1002
=> migrate:clean bakery command

app/sprinkles/core/assets/userfrosting/css/AdminLTE.css, app/sprinkles/core/assets/userfrosting/js/AdminLTE.js
Navigated around the site with no problems and didn't see any console errors, should be safe to merge.
=> Update to AdminLTE 2.3.11

app/sprinkles/admin/schema/requests/user/create.yaml, app/sprinkles/admin/src/Controller/UserController.php
Not sure if I picked the right base branch, let me know :)
This fixes some (I guess) typos in https://github.com/userfrosting/UserFrosting/pull/1017 such that it actually works (on my machine™️).
issue: https://github.com/userfrosting/UserFrosting/pull/764
=> Fix typos in user creation with initial password

app/sprinkles/admin/templates/forms/group.html.twig
Fix typos: missing `form.`  in `form.fields.hidden` for icon and description
Noticed that these two fields were not being hidden despite including them in `form.fields.hidden` in the controller.
=> Fix typos in form.fields.hidden

app/sprinkles/admin/locale/de_DE/messages.php, app/sprinkles/core/locale/de_DE/validate.php
As discussed in issue #1027 the updated german (de_DE) locals
=> German localisation

CHANGELOG.md, app/sprinkles/account/src/Authenticate/Authenticator.php, app/sprinkles/account/src/Database/Models/User.php
=> Fix for #1050 - User cache not flushed on model save 

app/sprinkles/admin/src/Controller/UserController.php, app/sprinkles/admin/templates/forms/partials/user-set-password.html.twig, app/sprinkles/admin/templates/forms/user-set-password.html.twig, app/sprinkles/admin/templates/modals/user-set-password.html.twig
Bug: editing a users password does not work, it always ends up as invalid because "the passwords don't match".
This fixes that by making the name of the password field flexible:
* 'password' on the user creation form
* 'value' on the edit password form (since that goes through admin's `UserController::updateField`)
this replaces https://github.com/userfrosting/UserFrosting/pull/1034
see also https://github.com/userfrosting/UserFrosting/pull/1030
I now see that the whole thing could've also been fixed by calling the password field `"value"` (and reverting the above PR), but that looks a bit weird IMHO. But let me know what you think!
=> Fix direct password edit

app/sprinkles/admin/schema/requests/user/edit-password.yaml
The input name in the rendered modal is `password` instead of `value`
See https://github.com/userfrosting/UserFrosting/blob/a8e6711fd5afd0572fc1581950f161b9581a8ffd/app/sprinkles/admin/templates/forms/partials/user-set-password.html.twig#L25
=> Fix edit password schema field name

app/sprinkles/admin/src/Sprunje/ActivitySprunje.php
Some activity logs can occur at the same second, so ordering just by date can show the results unordered. As per @lcharette suggestion, we can order by `occurred_at` AND `id`. That should gives better results.
=> Improve ordering by activity date

CHANGELOG.md, build/package.json, build/tasks/assets-install.js
Fix for issue where incompatible NPM packages would be run through browserify, killing asset install process
=> Make browserify more robust against package issues

app/sprinkles/account/src/Controller/AccountController.php, app/sprinkles/account/tests/Integration/Controller/AccountControllerTest.php
for https://github.com/userfrosting/UserFrosting/issues/1076
This only changes how attempts are counted, not how the blocking works.
If you got the password wrong often enough to be above the throttle limit, you still can't login, even if you have the correct password now (as that would defeat the whole point).
The big upside is that one can now configure `sign_in_attempts` to be *much* more strict (one could even start blocking after the first attempt).
Tested via throttler mock - let me know if you have better ideas :)
=> sign_in_attempt throttler: don't count successful logins

CHANGELOG.md, build/package.json, build/tasks/build.js
From the changelog;
- Client-side assets containing glob characters causing crashes when building assets.
- Fixed issue where merging of package dependencies would show as "undefined", resulting in debugging challenges where there are issues.
=> Hotfix assets update

CHANGELOG.md, docker/app/Dockerfile
Some of the UF Dependencies are not yet compatible with Composer 2.x so forcing downgrade to Composer 1.x
=> Force Composer 1.0 for Docker

app/sprinkles/core/templates/pages/abstract/error.html.twig
The error page content should be in a container so that it doesn't live right up against the edge of the DOM. Adding the `container` class to this div will fix it.
=> Update error.html.twig - add container

app/sprinkles/core/config/default.php, app/sprinkles/core/config/testing.php, app/sprinkles/core/src/Bakery/DebugCommand.php, app/sprinkles/core/src/ServicesProvider/ServicesProvider.php, app/sprinkles/core/src/Util/CheckEnvironment.php, app/system/Bakery/BaseCommand.php
See https://github.com/userfrosting/UserFrosting/issues/1098. Not sure if we want to merge this in for a revision or save for another minor version.
=> Replace getenv() with env()

app/sprinkles/admin/src/Controller/UserController.php
Back in 2019 a PR was approved to allow "No Group". It looks like the ability for admins to create users without a group was overlooked.
=> Foreign Key constraint fails when an admin attempts to create a new user

app/sprinkles/account/tests/Integration/Controller/AccountControllerTest.php
Fixed `AccountControllerTest` so that it doesn't fail when the registration is disabled in the main configuration.
=> Fix for AccountControllerTest when registration is disabled

app/sprinkles/admin/src/Controller/UserController.php
When the last role is removed from a user an exception occurs (BadRequest). It is feasible for a user to not have any roles IMO so this provides a default value in the case where all roles are removed (ie only the csrf is sent in the PUT request).  This is a bit of a special case because roles are an array and not a single value (which could be empty) unlike other cases.
=> Handle the case where all roles are removed from a user

app/sprinkles/account/tests/Integration/FindUniqueTest.php
`FindUniqueTest` fails in the accounts sprinkle when class mappings are changed for `user` and `group`.
=> Fix for FindUniqueTest when class mappings are changed

app/sprinkles/account/src/Account/Registration.php
With this patch, setting the default group to "null" in the configuration means that newly registered users default to not being in a group. Previously this caused a "Registration is broken" error.
Incidentally, the translation for "ACCOUNT.REGISTRATION_BROKEN" does not exist either...
=> Allowing no default group on register

app/sprinkles/account/src/Database/Migrations/v420/AddingForeignKeys.php
At one point I completely tore down my DB and tried rebuilding via migrations, with my own sprinkles in place. Somehow Bakery insisted on running the v420/AddingForeignKeys migration before most of the v400 migrations, so of course it errored and Bakery choked. I've added here the relevant dependencies, and Bakery was able to correctly run all my migrations with these changes.
=> StrykeSlammerII v420 patch 1

app/sprinkles/core/src/Error/Renderer/WhoopsRenderer.php
This fixes Integration test WhoopsRendererTest::testRenderWhoopsPage() and related issues with the Whoops error handler.  Creating a new Run instance here, as I can't find an existing one in UF's WhoopsRenderer.
(See related upstream issue https://github.com/filp/whoops/issues/752 and associated PR https://github.com/filp/whoops/pull/751)
(See also UF_ConfigManager issue https://github.com/lcharette/UF_ConfigManager/issues/8#issuecomment-1481604990)
=> Integrating upstream Whoops issue 752/PR 751
